# ----------------------------------------------------------------------------------- #
#                   Configuration for CNVkit-PureCN Pipeline                          #
# ----------------------------------------------------------------------------------- #

# ------------------
# I/O Parameters & Directories
# ------------------
samplesheet: "scripts/snakemake/samples.tsv"

dirs:
  purecn_setup: "results/01_purecn_setup"
  purecn_runs: "results/02_purecn_runs"
  purity_values: "results/03_purity_values"
  pon_creation: "results/04_pon_creation"
  cnvkit_runs: "results/05_cnvkit_runs"
  final_calls: "results/06_final_calls"
  final_vcfs: "results/07_final_vcfs"
  plots: "results/08_plots"
  logs: "logs"

# ------------------
# Reference Files (USER MUST UPDATE THESE PATHS)
# ------------------
reference_genome: "/path/to/your/ucsc.hg19.fasta"
targets_bed: "/path/to/your/targets.bed"
access_bed: "/path/to/your/access-5k-mappable.hg19.bed"
blacklist: "/path/to/your/genomic_blacklist.bed" # Generic blacklist for contaminants or problematic regions
purecn_normal_panel_vcf: "/path/to/your/normal_panel.vcf.gz"

# Optional annotation file for labeling genes if not present in the targets_bed.
# Comment out to disable annotation.
annotate_refFlat: "/path/to/your/refFlat.txt"

# ------------------
# Conda Environment Files
# ------------------
conda_envs:
  cnvkit: cnvkit
  purecn: purecn

# ------------------
# Helper Scripts Directory
# ------------------
helpers_dir: "scripts/helpers"

# ------------------
# Tool Parameters
# ------------------
purecn_genome: "hg19"
purecn_assay_name: "MyTumorAssay"
pon_qc_metric_threshold: 0.3
segment_threshold: 1.0e-4

# Skip PureCN analysis (set to true to skip purity estimation)
skip_purecn: false

# ------------------
# Plotting Parameters
# ------------------
genes_of_interest:
  - "TP53"
  - "MYC"
  - "EGFR"
  - "ERBB2"

# ------------------
# Resource Allocation
# ------------------
default_threads: 4
default_mem_mb: 16000
cnvkit_batch_mem_mb: 24000
